var schedule = {
    "1":  [["DEN", "OAK"], ["MIA", "NE"],  ["NYJ", "DAL"], ["ARI", "CAR"],
           ["SF",  "SEA"], ["SD",  "MIN"], ["WAS", "NYG"], ["HOU", "IND"],
           ["BAL", "PIT"], ["JAC", "TEN"], ["TB",  "DET"], ["STL", "PHI"],
           ["KC",  "BUF"], ["CLE", "CIN"], ["CHI", "ATL"], ["NO",  "GB"]],
    "2":  [["NYJ", "JAC"], ["NO",  "CHI"], ["TEN", "BAL"], ["PIT", "SEA"],
           ["WAS", "ARI"], ["CAR", "GB"],  ["MIN", "TB"],  ["DET", "KC"],
           ["BUF", "OAK"], ["IND", "CLE"], ["SF",  "DAL"], ["NE",  "SD"],
           ["MIA", "HOU"], ["DEN", "CIN"], ["ATL", "PHI"], ["NYG", "STL"]],
    "3":  [["BUF", "NE"],  ["CIN", "SF"],  ["CLE", "MIA"], ["TEN", "DEN"],
           ["MIN", "DET"], ["NO",  "HOU"], ["PHI", "NYG"], ["CAR", "JAC"],
           ["SD",  "KC"],  ["OAK", "NYJ"], ["STL", "BAL"], ["SEA", "ARI"],
           ["TB",  "ATL"], ["CHI", "GB"],  ["IND", "PIT"], ["DAL", "WAS"]],
    "4":  [["CHI", "CAR"], ["CIN", "BUF"], ["CLE", "TEN"], ["DAL", "DET"],
           ["STL", "WAS"], ["PHI", "SF"],  ["KC",  "MIN"], ["JAC", "NO"],
           ["HOU", "PIT"], ["SEA", "ATL"], ["ARI", "NYG"], ["SD",  "MIA"],
           ["GB",  "DEN"], ["OAK", "NE"],  ["BAL", "NYJ"], ["TB",  "IND"]],
    "5":  [["BUF", "PHI"], ["IND", "KC"],  ["MIN", "ARI"], ["NYG", "SEA"],
           ["TEN", "PIT"], ["CAR", "NO"],  ["JAC", "CIN"], ["HOU", "OAK"],
           ["SF",  "TB"],  ["NE",  "NYJ"], ["DEN", "SD"],  ["ATL", "GB"],
           ["DET", "CHI"]],
    "6":  [["ATL", "CAR"], ["CIN", "IND"], ["DET", "SF"],  ["GB",  "STL"],
           ["WAS", "PHI"], ["NYG", "BUF"], ["PIT", "JAC"], ["BAL", "HOU"],
           ["OAK", "CLE"], ["NE",  "DAL"], ["TB",  "NO"],  ["CHI", "MIN"],
           ["NYJ", "MIA"]],
    "7":  [["CLE", "SEA"], ["DET", "ATL"], ["TEN", "HOU"], ["MIA", "DEN"],
           ["NYJ", "SD"],  ["TB",  "CHI"], ["CAR", "WAS"], ["ARI", "PIT"],
           ["OAK", "KC"],  ["DAL", "STL"], ["MIN", "GB"],  ["NO",  "IND"],
           ["JAC", "BAL"]],
    "8":  [["TEN", "IND"], ["STL", "NO"],  ["NYG", "MIA"], ["CAR", "MIN"],
           ["BAL", "ARI"], ["HOU", "JAC"], ["BUF", "WAS"], ["DEN", "DET"],
           ["SF",  "CLE"], ["PIT", "NE"],  ["SEA", "CIN"], ["PHI", "DAL"],
           ["KC",  "SD"]],
    "9":  [["BUF", "NYJ"], ["DAL", "SEA"], ["NO",  "TB"],  ["IND", "ATL"],
           ["KC",  "MIA"], ["WAS", "SF"],  ["HOU", "CLE"], ["OAK", "DEN"],
           ["TEN", "CIN"], ["NE",  "NYG"], ["ARI", "STL"], ["SD",  "GB"],
           ["PIT", "BAL"], ["PHI", "CHI"]],
    "10": [["SD",  "OAK"], ["ATL", "NO"],  ["CHI", "DET"], ["CIN", "PIT"],
           ["CLE", "STL"], ["DAL", "BUF"], ["IND", "JAC"], ["KC",  "DEN"],
           ["MIA", "WAS"], ["PHI", "ARI"], ["TB",  "HOU"], ["CAR", "TEN"],
           ["SEA", "BAL"], ["SF",  "NYG"], ["NYJ", "NE"],  ["GB",  "MIN"]],
    "11": [["DEN", "NYJ"], ["ATL", "TEN"], ["CLE", "JAC"], ["DET", "CAR"],
           ["GB",  "TB"],  ["WAS", "DAL"], ["BAL", "CIN"], ["MIA", "BUF"],
           ["MIN", "OAK"], ["SF",  "ATL"], ["STL", "SEA"], ["CHI", "SD"],
           ["NYG", "PHI"], ["NE",  "KC"]],
    "12": [["DET", "GB"],  ["DAL", "MIA"], ["BAL", "SF"],  ["ATL", "MIN"],
           ["CIN", "CLE"], ["TEN", "TB"],  ["IND", "CAR"], ["JAC", "HOU"],
           ["STL", "ARI"], ["NYJ", "BUF"], ["OAK", "CHI"], ["SEA", "WAS"],
           ["PHI", "NE"],  ["SD",  "DEN"], ["KC",  "PIT"], ["NO",  "NYG"]],
    "13": [["SEA", "PHI"], ["BUF", "TEN"], ["CHI", "KC"],  ["CLE", "BAL"],
           ["MIA", "OAK"], ["NO",  "DET"], ["PIT", "CIN"], ["TB",  "CAR"],
           ["WAS", "NYJ"], ["HOU", "ATL"], ["MIN", "DEN"], ["SF",  "STL"],
           ["NYG", "GB"],  ["ARI", "DAL"], ["NE",  "IND"], ["JAC", "SD"]],
    "14": [["PIT", "CLE"], ["CIN", "HOU"], ["DET", "MIN"], ["GB",  "OAK"],
           ["TEN", "NO"],  ["MIA", "PHI"], ["NYJ", "KC"],  ["WAS", "NE"],
           ["CAR", "ATL"], ["JAC", "TB"],  ["BAL", "IND"], ["DEN", "CHI"],
           ["ARI", "SF"],  ["SD",  "BUF"], ["DAL", "NYG"], ["SEA", "STL"]],
    "15": [["ATL", "JAC"], ["TB",  "DAL"], ["BUF", "MIA"], ["CHI", "SEA"],
           ["IND", "TEN"], ["KC",  "GB"],  ["STL", "CIN"], ["MIN", "NO"],
           ["NYG", "WAS"], ["HOU", "CAR"], ["OAK", "DET"], ["PHI", "NYJ"],
           ["ARI", "CLE"], ["DEN", "NE"],  ["SD",  "BAL"], ["SF",  "PIT"]],
    "16": [["IND", "HOU"], ["BUF", "DEN"], ["CIN", "ARI"], ["TEN", "JAC"],
           ["KC",  "OAK"], ["NE",  "MIA"], ["NYJ", "NYG"], ["PIT", "STL"],
           ["WAS", "MIN"], ["CAR", "TB"],  ["BAL", "CLE"], ["DET", "SD"],
           ["SEA", "SF"],  ["DAL", "PHI"], ["GB",  "CHI"], ["NO",  "ATL"]],
    "17": [["ATL", "TB"],  ["CIN", "BAL"], ["CLE", "PIT"], ["GB",  "DET"],
           ["JAC", "IND"], ["HOU", "TEN"], ["STL", "SF"],  ["MIA", "NYJ"],
           ["MIN", "CHI"], ["NE",  "BUF"], ["NO",  "CAR"], ["NYG", "DAL"],
           ["PHI", "WAS"], ["ARI", "SEA"], ["OAK", "SD"],  ["DEN", "KC"]]
};
